@startuml login

start

:Benutzer gibt Login Daten ein;
:Daten werden geprüft;
while (Daten okay?) is (nein))
    :Benutzer bekommt Fehlermeldung;
    :Benutzer gibt Daten erneut ein;
endwhile
:Benutzer wird eingeloggt;
:Token wird gesetzt;
:Benutzer wird zu Home weitergeleitet;

stop

@enduml