version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: shopster
      MARIADB_USER: shopster
      MARIADB_PASSWORD: fgICCsMrKmrQU4U1
    ports:
      - '3306:3306'
    expose:
      - '3306'
